spring:
  security:
    resource:
      # 静态资源
      - /favicon-*.png/*
      - /*/webjars/js/*.js
      - /*/webjars/css/*.css
      - /*/doc.html
      - /*/swagger-resources
      - /*/favicon.ico
      - /*/v2/api-docs
      - /*/webjars/*/*
      # 监控
      - /actuator
      - /actuator/health
      - /actuator/health/*
      - /actuator/info
      - /actuator/env
      - /actuator/httptrace
      - /actuator/mappings
      - /actuator/threaddump
      - /actuator/heapdump
      - /actuator/loggers
      - /actuator/loggers/*
      - /actuator/logfile
      - /actuator/metrics
      - /actuator/metrics/*
      - /actuator/beans
      - /actuator/caches
      - /actuator/configprops
      - /actuator/scheduledtasks
      - /actuator/prometheus